services:
  - type: web
    name: vortex
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install qrcode[pil] Pillow
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 7861
 
